### ISSUE TITLE
local cargo test failure after 2-3 rounds

### ISSUE THREAD

**Issue by kelwang** [influxdata/flux-lsp#107]
to reproduce this issue, navigate to root directory
failures:

run `cargo test` several times, until you see the errors

======================================
---- speculate_0::Goto_definition::test_returns_correct_response stdout ----
thread 'speculate_0::Goto_definition::test_returns_correct_response' panicked at 'called `Result::unwrap()` on an `Err` value: "unknown uri: file:///Users/kelwang/git/flux-lsp/tests/fixtures/ok.flux"', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- speculate_0::Find_references::test_returns_correct_response stdout ----
thread 'speculate_0::Find_references::test_returns_correct_response' panicked at 'called `Result::unwrap()` on an `Err` value: "unknown uri: file:///Users/kelwang/git/flux-lsp/tests/fixtures/ok.flux"', src/libcore/result.rs:1165:5

---- speculate_0::Document_change::when_ok::test_returns_the_correct_response stdout ----
thread 'speculate_0::Document_change::when_ok::test_returns_the_correct_response' panicked at 'called `Result::unwrap()` on an `Err` value: "unknown uri: file:///Users/kelwang/git/flux-lsp/tests/fixtures/ok.flux"', src/libcore/result.rs:1165:5

failures:
    speculate_0::Document_change::when_ok::test_returns_the_correct_response
    speculate_0::Find_references::test_returns_correct_response
    speculate_0::Goto_definition::test_returns_correct_response

test result: FAILED. 11 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test handlers

**Comment by kelwang** [comment]
i suspect something related to the global cache

**Comment by kelwang** [comment]
looks like single thread mode is working. closing it for now
